### ISSUE TITLE
fix: Selector.chain() not producing the desired output

### ISSUE THREAD

**Issue by i-am-ijaz** [schultek/jaspr#122]
**Description**

Selector.chain not producing the desired output

**Steps To Reproduce**

1. I want to implement the style like this using the StyleRules
![image](https://github.com/schultek/jaspr/assets/25157495/45275411-7c74-43d2-bb08-d17b700bac6f)
2. I applied the style using the Selector.chain method
![image](https://github.com/schultek/jaspr/assets/25157495/75a90d17-0f4c-472d-8f22-3e83720b82e4)
3. After inspecting the web page. I came to know that it producing the chain selector 
without any spacing (See the bottom right corner of the image) _Sorry for this bad screenshot_:
![image](https://github.com/schultek/jaspr/assets/25157495/28b8d872-7a5b-46cc-ba0c-0fa30f094327)

**Expected Behavior**

There must be a space between the chain of selectors otherwise it would not work

**Comment by schultek** [comment]
Sorry this is actually not a bug.

You can use `Selector.combine` instead of `.chain`.

Combine is for selecting child elements (e.g. `div #main` -> a element with the id 'main' that is a child of a div)
Chain is for having multiple selectors for a single element (e.g. `div#main` -> a div with the id 'main')

This is totally on me since the code is not documented anywhere. This is on the long list of todos :)
