### ISSUE TITLE
feat: add jaspr_bloc

### ISSUE THREAD

**Issue by evstegneych** [schultek/jaspr#144]
**Description**

https://pub.dev/packages/flutter_bloc

This is the best part in the world of dart/flutter! Billions of developers use it, so we need to implement it

**Additional Context**

**Comment by schultek** [comment]
There is already https://github.com/f-person/jaspr_bloc by @f-person

Maybe you can join forces and make it ready for publishing.

**Comment by schultek** [comment]
Closing this as not planned.

For some additional context: My intention behind doing jaspr_riverpod are mostly about showcasing how such a package can be ported to jaspr. I don't plan on adding any more of these because I can't maintain a growing number of these (the next guy would ask for another package and so on). They are better done by the community anyways.
