### ISSUE TITLE
`jaspr generate` doesn't exist, but the docs still shows this

### ISSUE THREAD

**Issue by exaby73** [schultek/jaspr#236]
**Description**

I am trying to generate a static site of a project I initially set up using SSR. The [docs](https://docs.page/schultek/jaspr/core/ssg) say I should use `jaspr generate`.

**Steps To Reproduce**

See https://docs.page/schultek/jaspr/core/ssg

**Expected Behavior**

Docs should be clear about how to generate a static site, even if the project was initially generated with the SSR preset

**Additional Context**

Output of `jaspr generate`:

```console
Could not find a command named "generate".

Usage: jaspr <command> [arguments]

Global options:
-h, --help                 Print this usage information.
-v, --version              Print the current version info.
    --enable-analytics     Enable anonymous analytics.
    --disable-analytics    Disable anonymous analytics.

Available commands:

Project
  build    Builds the full project.
  create   Creates a new jaspr project.
  serve    Runs a development server that serves the jaspr app and reloads based on file system updates.

Tooling
  clean    Cleans the project directory.
  doctor   Shows information about the environment and project.
  update   Updates the jaspr cli.

Run "jaspr help <command>" for more information about a command.
```

**Comment by exaby73** [comment]
Yeah I figured it out :). Could we also add a section explaining the modes, and its possible values? Also would be awesome to see docs on changes need to be done to turn a client only site to SSG or SSR. A migration guide of sorts I guess. I'm new to Jaspr, just decided to use it for a serious project so I don't think I'm the best one to make a PR for those docs, else I would. Thanks for your hard work on this. Hopefully we can get asset hashing into Jaspr soon too, for support on Globe :)

**Comment by schultek** [comment]
Fixed the docs.

Regarding asset hashing, I'm still waiting for general asset support on globe before I can test this out. Any progress there?

**Comment by lesnitsky** [comment]
@schultek asset support is on our roadmap, however, some changes will still be required from jaspr side as well. In general:
- we will allow to specify which assets need to be uploaded to CDN
   - those assets MUST be hashed, otherwise there will be no way to push an update. We can invalidate our internal CDN cache, but browser cache is not up to us, that's why asset hashing is required
- we will allow _some_ files to be hosted alongside a compiled dart executable in read-only mode, but this is likely to happen much later. What would have been a nice addition to jaspr is an ability to "bundle" static assets into a compiled dart executable. It could be an in-memory map `(path => base64 encoded file content)` + some IO overrides.

**Comment by schultek** [comment]
What I don't quite get is how would you support projects that are not using a framework like jaspr. I.e. just shelf with some static assets. Would user need to write a manifest and hash manually?
