### ISSUE TITLE
`build` method middleware or wrappers to support MobX, hooks, Pods and other framework-wide functionalities

### ISSUE THREAD

**Issue by juancastillo0** [schultek/jaspr#26]
Hi, thanks for your work!

This may be a weird feature request which will make the package a bit different from Flutter and there may be performance considerations. However, the usability improvements would be great, in my opinion.

The idea is to provide a middleware for rendering Components, a function that wraps the executions of all build methods, to do various things.

For example, for registering and tracking dependencies that rebuild the Widget when they change. I believe the javascript framework https://www.solidjs.com/ is based on this concept, similar to MobX's tracking of dependencies. Through testing the package I have implemented some MobX and hooks bindings for Components. In [this file](https://github.com/juancastillo0/cidart/blob/0bb72153546754e99f8a024c46d337e81de7b867/web_client/lib/mobx_hooks.dart) you can see the main hooks logic and also the tracking of dependencies within build methods of `StatelessObserverComponent` similar to the one in [`package:flutter_mobx`](https://pub.dev/documentation/flutter_mobx/latest/flutter_mobx/StatelessObserverWidget-class.html), however this one also supports hooks. In Flutter this is a problem it's difficult to use `package:flutter_mobx` and `package:flutter_hooks` (two packages implementing Elements) without nesting that the composing of middleware or multiple wrappers can solve. There are no automatic test, but I have tested them manually and you can try the deployed html in [gh-pages](https://juancastillo0.github.io/cidart/). More hooks, using the same infrastructure, are implemented in [this hooks file](https://github.com/juancastillo0/cidart/blob/0bb72153546754e99f8a024c46d337e81de7b867/web_client/lib/hooks.dart). 

This is similar to some work I did in a `package:deact` [fork](https://github.com/juancastillo0/deact). However, in that fork a kind of middleware or wrapper is implemented for all build methods, not only for those in `StatelessObserverWidget`. Which is nicer, since one does not worry about using the appropriate Widget (every build method is being tracked). You would not have to worry where to place them, one would register the middleware for the whole app (or a section) and use observables (or hooks) that are tracked by the middleware. They would all be tracked and rebuild the widgets in the places where the observables are used. There are perhaps some performance implications. Maybe some kind of similar middleware or wrapper for build functions could be provided as API. In this case, all that is needed is a value that saves state in the element and can be disposed (`HookCtx`), the `markNeedsBuild` method and a function that executes the build method. As shown in this  [code](https://github.com/juancastillo0/cidart/blob/0bb72153546754e99f8a024c46d337e81de7b867/web_client/lib/mobx_hooks.dart#L67):

```dart
List<Component> _mobxHooksWrapper(
  HookCtx ctx,
  void Function() markNeedsBuild,
  List<Component> Function() next,
) {
  final previousCtx = _ctx;
  _ctx = ctx;
  final List<Component> children = useTrack(
    next,
    markNeedsBuild,
    name: ctx.hashCode.toString(),
  );
  _ctx = previousCtx;
  return children;
}
```

`_mobxHooksWrapper` is executed on every build and provides MobX tracking with `useTrack` and hooks support with the `HookCtx` that is saved in the `ComponentElement`.

I the [repo](https://github.com/juancastillo0/cidart/), I am always using the implemented `StatelessObserverComponent` or `StatefulObserverComponent` since they provide hooks and MobX tracking. To make sure I use them I import `package:jaspr` though a `prelude.dart` file that overrides `StatelessComponent` to `StatelessObserverComponent`.

Other use cases may include some kind of profiling, however there are probably other ways to do it too. Maybe some kind of dynamic (can be turned on and off) profiling of certain parts of the Widget tree though similar middleware.

Maybe unrelated, but maybe some API for dependency injection can be explored though a middleware also. Within the repo there is also an [implementation](https://github.com/juancastillo0/cidart/blob/0bb72153546754e99f8a024c46d337e81de7b867/web_client/lib/pod_scope.dart) of dependency injection, similar to `package:riverpod`. For watching, I am relying on MobX's dependency tracking, the pod's value in a pod scope is immutable. However, their properties may be mutable and, if they are MobX observables, everywhere they are used, they are being tracked (provided one uses `StatelessObserverComponent`). For disposing, the values are disposed when the scope is disposed which is created using the `_InheritedPodScope` InheritedWidget. One could also create scopes outside of jaspr, but within jasper one reads the pod values with an extension over `BuildContext` that implements a `T pod<T>(Pod<T> pod)` method that reads the closest `_InheritedPodScope` and retrieves the value. Pods can be global or scoped. If they are global a single instance will be created for all scopes within the tree and will be disposed when the whole tree is disposed. If it's not global, then it will be created within a subtree, all children of the scope will be have access to the same instance, but there could be other instances in other scopes (subtrees).

In this case maybe a middleware could be implemented to support the `autoDispose` feature in riverpod, where the dependencies are saved within the element and when the Pod's Element dependencies are disposed, then the Pod is disposed.

In general, this would allow for the framework to be extensible and to test or evaluate framework-wide functionalities that may be implemented natively by the framework in the future, or maybe just leave them as separate packages.

Thanks!

**Comment by schultek** [comment]
Thanks for this issue. It took me a bit to get what you are proposing, but I think I understand now. There are a few things to unpack:

I'm on your side when it comes to letting jaspr form its own path. What I mean by that is while jasprs core framework implementation is heavily derived from Flutter, it does not need to limit itself by the same. So I'm open to deviate from flutters implementation ([and already did in a few cases](https://github.com/schultek/jaspr/tree/main/packages/jaspr_riverpod)) where it has some clear advantages / improvements.

Also as a framework, it should provide enough flexibility for both app and package authors to implement their preferred way of doing things (e.g. state management, architecture etc). However there is a tight balance to hold between giving more power to package authors by opening up the core framework implementation and keeping a handle on performance and stability.

With middleware that wraps and controls the execution of arbitrary build methods, it can completely mess with the internal build system. I feel that there are too many performance and stability concerns where using this could easily introduce heavy performance hits, hard to catch bugs or  make the build system instable. It really seems impossible to write a stable framework around a feature like this, and marking a feature like this as 'potentially unstable' or 'can break stuff' goes against my idea of a user-friendly framework.

However there might be another way of hooking into the general build process by using global observers that can watch the build process without controlling it. There could be a `ComponentsObserver` that implements `willRebuildElement(Element e)` and `didRebuildElement(Element e)` which are called before and after an element is built. Such an observer would then be globally registered, similar to how [WidgetsBindingObserver](https://api.flutter.dev/flutter/widgets/WidgetsBindingObserver-class.html) works in Flutter. I'm not familiar with the internal workings of mobx, but maybe this could still work since you could track what observers are accessed between those two observer calls for an element.

Please let me know what you think of this.

PS: Regarding the part on riverpod and especially autoDispose, did you look at jaspr_riverpod and how it is implemented? It already uses a `didRebuildDependent(Element e)` method on `InheritedElement` that hooks into the build phase of an element.

**Comment by juancastillo0** [comment]
Great, thank you for the thorough response!

Yes I definitely agree with you, it could open up too much of the framework and have unintended consequences. 

To support hooks and MobX tracking, I believe it does not need to be a middleware, in the sense that it does not need to modify the input or output of the build method. As you said, a `ComponentsObserver` I believe would work. From the testing I have made I think all that is needed are these abilities:

- Know when the element's build execution starts and ends (`willRebuildElement` and `didRebuildElement`).
  - to identify the current element when a hook or observer is used
- Know when the element disposes (`didUnmountElement`)
  - to remove the tracking for MobX and dispose of all the hook effects/state created within an element
- Save state for the element (With the reference to the element from `willRebuildElement`, one could save state)
  - to know what where the previously used hooks and save the tracked observables
- Rebuild the element (With the reference to the element, one could execute `markNeedsBuild`)
  - to let the framework know when a dependency of the build method has changed. In the code example, I was using MobX observables for hook states, so they where being tracked automatically. (And the MobX state was created and disposed using hooks)

I believe experimenting with the `ComponentsObserver` would be great. Maybe adding a `didUnmountElement` would also allow to dispose the state in `ComponentsObserver` associated with the element.

> PS: Regarding the part on riverpod and especially autoDispose, did you look at jaspr_riverpod and how it is implemented? It already uses a `didRebuildDependent(Element e)` method on `InheritedElement` that hooks into the build phase of an element.

Awesome! It is much nicer to use the `BuildContext` directly without the need for `ConsumerWidget`, I had not looked at it carefully, thank you. Knowing when a dependent stops listening with `deactivateDependent` and the `didRebuildDependent` are great additions. The idea about the Pods above would not be necessary, what you have done to `InheritedElement` solves it.

Do you think I could open a PR with something like `ComponentsObserver`? Should it be scoped within the component tree? or global for all components? I think either way could work, maybe scoping it would allow for more granular placing. But something global would be easier to think about and implement. What should the argument for `willRebuildElement` and friends be? Do you think we have to restrict the `Element` class into a simpler abstraction? For the functionalities discussed only a unique reference (the element itself, perhaps) and the `markNeedsBuild` function are needed.

Thank again for the response and all your work!

**Comment by schultek** [comment]
Awesome, feel free to open a PR for this, I would be happy to integrate this.

I think scoping this to the component tree would be the preferred way, since it fits in with the component model and gives more possibilities. I think the imlpementation should be similar to `InheritedComponent` that the lookup time is O(1). Maybe something like an `ObserverComponent` that creates an  `ObserverElement` where subclasses override the `willRebuildElement` etc methods. Passing the `Element` to those methods should be fine, this also aligns with `InheritedElement `.
