### ISSUE TITLE
Unwanted space in inline text

### ISSUE THREAD

**Issue by adriank** [schultek/jaspr#313]
**Description**

```dart
h1([
          b([text('this')]),
          text('and'),
          b(classes: 'font-semibold', [text('that')]),
          span([text('.')]),
        ])
```

results in "**this** and **that** ." instead of "**this** and **that**.".

This is probably because Jaspr outputs each of the list elements in separate line with indenting. Can it be changed somehow?

**Comment by schultek** [comment]
Oh ok, I will have to change the heuristic how to format the outputted html.

**Comment by adriank** [comment]
Or just provide option to remove all white space between tags. HTML minifiers do this, so I wouldn't suspect any problems. If space is needed, developers would need to wrap them in <span>s.

**Comment by schultek** [comment]
I think I found a nice way to improve this.

My main challenge is that I want to
a) format the server-rendered html nicely with newlines and indentation of child html nodes, but also
b) don't affect the displayed html (which failed in your case)

I will update the implementation to apply formatting based on the tag:

- for `pre`, `code` and `span` elements no newlines or indentation is added at all, keeping the output html exactly as it was given by the user
- for `p`, `a`, and `h1-6` elements newlines and indentation are only added at the beginning or end of the element (because such whitespaces are ignored) or after a child when the child already has a trailing whitespace (because multiple whitespaces are collapsed).
- for other elements newlines and whitespaces are always added 

From my testing this should give the intended output in 99% of all cases while still formatting nicely the output html.

This will solve the case above where now no additional whitespace is added between two texts that don't already have a whitespace (e.g. `that` and `.`)

As an 'escape hatch' option for users (e.g. when whitespace is still added where the user doesn't want it), wrapping some parts in a `span` will prevent any unwanted formatting.


@adriank What do you thing about this?
You can also test this using:
```dart
dependency_overrides:
  jaspr:
    git:
      url: https://github.com/schultek/jaspr
      path: packages/jaspr
      ref: improvement/html-formatting
```

**Comment by adriank** [comment]
I didn't have time to check it. Does it handle the case with link at the end like "<a>link</a>." ?

**Comment by schultek** [comment]
If it's wrapped in a `p`, `h1-6` or `span` yes.
